export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT = 'LOGOUT';

export const PASSWORD_INPUT_CHANGE = 'PASSWORD_INPUT_CHANGE';
export const UPDATE_SEARCH_VALUE = 'UPDATE_SEARCH_VALUE';

export const ADD_TODO = 'ADD_TODO';
export const ADD_TODO_INPUT_UPDATE = 'ADD_TODO_INPUT_UPDATE';
export const FETCH_TODOS = 'FETCH_TODOS';
export const FETCH_TODOS_SUCCESS = 'FETCH_TODOS_SUCCESS';
export const FETCH_TODOS_ERROR = 'FETCH_TODOS_ERROR';
export const REMOVE_TODO = 'REMOVE_TODO';
export const SORT = 'SORT';
export const TOGGLE_ADD_TODO_MODAL = 'TOGGLE_ADD_TODO_MODAL';
export const TOGGLE_ACTIVE = 'TOGGLE_ACTIVE';
export const TOGGLE_COMPLETED = 'TOGGLE_COMPLETED';
export const TOGGLE_TODO = 'TOGGLE_TODO';
